### ISSUE TITLE
ApiVersion not being supplied when updating reconcile status

### ISSUE THREAD

**Issue by HonakerM** [IBM/oper8#72]
## Describe the bug

When updating the CR status during [reconciliation](https://github.com/IBM/oper8/blob/d6513835f1e230384354c6d119e9f15c3cfc3970/oper8/reconcile.py#L577) we are not passing in the ApiVersion. This can cause errors if there are multiple resources with the same Kind like the following:
```
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]   Operation [<bound method OpenshiftDeployManager._set_status of <oppy.deploy_manager.openshift_deploy_manager.OpenshiftDeployManager object at 0x7f5a437f8460>>] failed to execute: Multiple matches found for {'api_version': None, 'kind': 'TemporaryPatch'}: [<Resource(somegroup/v1/temporarypatches)>, <Resource(othergroup/v1/temporarypatches)>]
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]   Traceback (most recent call last):
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]     File "/usr/local/lib/python3.9/site-packages/oppy/deploy_manager/openshift_deploy_manager.py", line 405, in _retried_operation
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]       self._run_individual_operation_with_retries(
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]     File "/usr/local/lib/python3.9/site-packages/oppy/deploy_manager/openshift_deploy_manager.py", line 455, in _run_individual_operation_with_retries
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]       return operation(resource_definition=resource_definition, **kwargs)
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]     File "/usr/local/lib/python3.9/site-packages/oppy/deploy_manager/openshift_deploy_manager.py", line 760, in _set_status
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]       resource_handle = self.client.resources.get(api_version=api_version, kind=kind)
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]     File "/usr/local/lib/python3.9/site-packages/openshift/dynamic/discovery.py", line 188, in get
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]       raise ResourceNotUniqueError('Multiple matches found for {}: {}'.format(kwargs, results))
2024-05-22T21:25:32.318493 [OSFTD:WARN:140025764513600]   kubernetes.dynamic.exceptions.ResourceNotUniqueError: Multiple matches found for {'api_version': None, 'kind': 'TemporaryPatch'}: [<Resource(somegroup/v1/temporarypatches)>, <Resource(othergroup/v1/temporarypatches)>]
2024-05-22T21:25:32.318844 [STTUS:WARN:140025764513600]   Failed to update status for [namespace/TemporaryPatch/resource]
``` 

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version:
- Library version:

## Sample Code

Please include a minimal sample of the code that will (if possible) reproduce the bug in isolation

## Observed behavior

What you see happening (error messages, stack traces, etc...)

**Comment by HonakerM** [comment]
This was resolved by the above PR
